# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ERPoWIubz1Ef4cSXdoyv3t2jcaDW43Sp
"""

import pandas as pd

data1 = open('/content/Raw_Skills_Dataset.csv')

data2 = open('/content/Example_Technical_Skills.csv')

fileone = data1.readlines()
filetwo = data2.readlines()
data1.close()
data2.close()

outFile = open('update.csv', 'w')
x = 0
for i in fileone:
    if i != filetwo[x]:
        outFile.write(filetwo[x])
    x += 1
outFile.close()

technology_skills = pd.read_csv('/content/update.csv')

technology_skills

technology_skills.isna().any()

technology_skills.duplicated()

tech=technology_skills.drop_duplicates(subset=None, keep='first', inplace=False, ignore_index=False)

tech.to_csv('/content/techno_skills.csv')